services:
  db:
    image: mysql:8.4
    # CAMBIO: Nombre del contenedor único
    container_name: cge_asistencia_db
    environment:
      - MYSQL_ROOT_PASSWORD=Tics.2025*
      - MYSQL_DATABASE=cge_asistencia_db
    volumes:
     # CAMBIO: Nombre del volumen único para los datos
      - cge_asistencia_db_data:/var/lib/mysql
    ports:
      - "3311:3306"
  web:
    build: .
    # CAMBIO: Nombre del contenedor único
    container_name: cge_asistencia_php
    ports:
    # CAMBIO: Nuevo puerto para acceder a esta aplicación
      - "8092:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    # CAMBIO: Nombre del contenedor único
    container_name: cge_asistencia_pma
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=Tics.2025*
    ports:
    # CAMBIO: Nuevo puerto para acceder a este phpMyAdmin
      - "8093:80"
    depends_on:
      - db

volumes:
    # CAMBIO: Definición del nuevo volumen
    cge_asistencia_db_data: